name: build-and-deploy

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        
      # a standard step for GitHub actions on Node
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: NoJekyll
        run: touch out/.nojekyll

      # - name: Install, Build & Export
      #   run: |
      #     npm install
      #     npm run build
      #     npm run export
      #     touch out/.nojekyll

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: out